version: '3'

services:
  database:
      build:
        context: ./Database
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 201901055
      networks:
        - mynet

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - mynet

  backend:
    build:
      context: ./Backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
