version: '3'

services:
  database:
    build:
      context: ./Database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 201901055
    volumes:
      - base_mysql:/var/lib/mysql
    networks:
      - mynet

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - mynet

  backend:
    build:
      context: ./Backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DB_USER: root
      DB_PASSWORD: 201901055
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: proyecto1
    privileged: true
    pid: host
    restart: always
    volumes:
      - type: bind
        source: /proc
        target: /proc
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  base_mysql:
