apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdeployment_grpc
  namespace: so1  
spec:
  selector:  
    matchLabels:
      role: deployment1  
  replicas: 1
  template: 
    metadata:
      labels:
        role: deployment1 
    spec:
      containers:  
      - name: cliente_grcp 
        image: angegt3/cliente_grcp 
        ports:  
        - containerPort: 3000  
      - name: servidor_grcp  
        image: angegt3/servidor_grcp  
        ports: 
        - containerPort: 3001


---
apiVersion: v1
kind: Service
metadata:
  name: service-proyecto2 
spec:
  ports: 
  - port: 3000  
    targetPort: 3000  
  selector:  
    role: grpc-ruta  
