apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  namespace: so1
  labels:
    app: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: angegt3/kafka-producer
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  selector:
    app: kafka-producer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP