apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: so1  
spec:
  selector:  
    matchLabels:
      role: consumer
  replicas: 3
  template: 
    metadata:
      labels:
        role: consumer
    spec:
      containers:  
      - name: consumer-container
        image: angegt3/golang-consumer
        env:
        - name: REDIS_HOST
          value: "redis.monitoring.svc.cluster.local"
        - name: REDIS_AUTH
          value: "YOUR_PASSWORD"
        ports:  
        - containerPort: 3002  
          protocol: TCP  
