[package]
name = "mi_servidor"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = "0.11.5"



[[bin]]
name = "main"
path = "main.rs"